/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminTypesRouteImport } from './routes/admin/types'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerOnboardingRouteImport } from './routes/seller.onboarding'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as SellerReviewsRouteImport } from './routes/seller/reviews'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SellerProductsIndexRouteImport } from './routes/seller/products/index'
import { Route as SellerProductsNewRouteImport } from './routes/seller/products/new'
import { Route as SellerProductsIdEditRouteImport } from './routes/seller/products/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTypesRoute = AdminTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/shops/$slug',
  path: '/shops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsIdEditRoute = SellerProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => SellerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller': typeof SellerRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/types': typeof AdminTypesRoute
  '/api/health': typeof ApiHealthRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/seller/products/$id/edit': typeof SellerProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/types': typeof AdminTypesRoute
  '/api/health': typeof ApiHealthRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/seller': typeof SellerIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/seller/products': typeof SellerProductsIndexRoute
  '/seller/products/$id/edit': typeof SellerProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller': typeof SellerRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/types': typeof AdminTypesRoute
  '/api/health': typeof ApiHealthRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
  '/seller/products/$id/edit': typeof SellerProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/seller'
    | '/verify-email'
    | '/account/addresses'
    | '/account/wishlist'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/types'
    | '/api/health'
    | '/products/$slug'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/reviews'
    | '/shops/$slug'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/seller/'
    | '/account/orders/$id'
    | '/api/auth/$'
    | '/seller/products/new'
    | '/account/orders/'
    | '/seller/products/'
    | '/seller/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/account/addresses'
    | '/account/wishlist'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/types'
    | '/api/health'
    | '/products/$slug'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/reviews'
    | '/shops/$slug'
    | '/account'
    | '/admin'
    | '/products'
    | '/seller'
    | '/account/orders/$id'
    | '/api/auth/$'
    | '/seller/products/new'
    | '/account/orders'
    | '/seller/products'
    | '/seller/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/seller'
    | '/verify-email'
    | '/account/addresses'
    | '/account/wishlist'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/types'
    | '/api/health'
    | '/products/$slug'
    | '/seller/onboarding'
    | '/seller/orders'
    | '/seller/reviews'
    | '/shops/$slug'
    | '/account/'
    | '/admin/'
    | '/products/'
    | '/seller/'
    | '/account/orders/$id'
    | '/api/auth/$'
    | '/seller/products/new'
    | '/account/orders/'
    | '/seller/products/'
    | '/seller/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerRoute: typeof SellerRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ShopsSlugRoute: typeof ShopsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/types': {
      id: '/admin/types'
      path: '/types'
      fullPath: '/admin/types'
      preLoaderRoute: typeof AdminTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/shops/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products/$id/edit': {
      id: '/seller/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/seller/products/$id/edit'
      preLoaderRoute: typeof SellerProductsIdEditRouteImport
      parentRoute: typeof SellerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminTypesRoute: typeof AdminTypesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminTypesRoute: AdminTypesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerProductsNewRoute: typeof SellerProductsNewRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
  SellerProductsIdEditRoute: typeof SellerProductsIdEditRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
  SellerProductsIdEditRoute: SellerProductsIdEditRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerRoute: SellerRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  ApiHealthRoute: ApiHealthRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ShopsSlugRoute: ShopsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
