#!/usr/bin/env bash
# Pull-based deploy for a single-server demo host (same pattern as sme-erp).
#
#   deploy/deploy.sh            deploy origin/main if not deployed yet (cron: every minute)
#   deploy/deploy.sh --force    redeploy now (e.g. after editing .env)
#
# First run generates .env with random secrets (server-local, never committed;
# later runs never touch it). Everything runs in Docker; the only published
# port is the proxy on 127.0.0.1:$PROXY_PORT, which cloudflared routes publicly.
set -euo pipefail

cd "$(dirname "$0")/.."
COMPOSE=(docker compose -f docker-compose.prod.yml)
BRANCH=main
PORT="${PROXY_PORT:-30002}"

log() { echo "$(date -u +%FT%TZ) $*"; }

# One deploy at a time (cron fires every minute; a build can take longer).
exec 9>.deploy.lock
flock -n 9 || exit 0

if [[ ! -f .env ]]; then
  log "generating .env"
  secret() { openssl rand -hex "$1"; }
  pg_password=$(secret 16)
  cat > .env <<EOF
# Generated by deploy/deploy.sh on $(date -u +%F) — server-local, never committed.
PROXY_PORT=${PORT}
# Public URL users reach the site on. Set it to https://<your-hostname> once the
# Cloudflare tunnel route exists, then run: deploy/deploy.sh --force
PUBLIC_URL=http://localhost:${PORT}

POSTGRES_PASSWORD=${pg_password}
DATABASE_URL=postgres://ecommerce:${pg_password}@postgres:5432/ecommerce
S3_BUCKET=products
S3_ACCESS_KEY=ecommerce
S3_SECRET_KEY=$(secret 16)
BETTER_AUTH_SECRET=$(secret 32)

# Demo host: demo shop/products/users seeded on every deploy (idempotent);
# sign-up needs no email verification (mail goes to an internal sink).
ALLOW_DEMO_SEED=true
AUTH_REQUIRE_EMAIL_VERIFICATION=false
SUPER_ADMIN_EMAIL=admin@example.com
SUPER_ADMIN_PASSWORD=$(secret 12)
# demo seller@dev.local / buyer@dev.local
DEMO_USER_PASSWORD=$(secret 6)
PAYMENT_PROVIDER=fake
EOF
  chmod 600 .env
  FORCE=1
fi

git fetch --quiet origin "$BRANCH"
target=$(git rev-parse "origin/$BRANCH")
deployed=$(cat .deployed-sha 2>/dev/null || true)
failed=$(cat .deploy-failed-sha 2>/dev/null || true)
if [[ "${1:-}" != "--force" && -z "${FORCE:-}" && ( "$target" == "$deployed" || "$target" == "$failed" ) ]]; then
  exit 0  # already deployed — or this exact commit already failed (push a fix or --force)
fi

# A failed deploy is remembered so cron does not rebuild it every minute.
trap 'echo "$target" > .deploy-failed-sha; log "deploy FAILED for ${target:0:7}"' ERR

log "deploying ${target:0:7}"
git reset --quiet --hard "$target"
# `up` runs the one-shot migrate service (migrations + seed) before web/worker
"${COMPOSE[@]}" up -d --build --remove-orphans

port=$(grep '^PROXY_PORT=' .env | cut -d= -f2)
for _ in $(seq 1 60); do
  curl -fsS "http://127.0.0.1:${port}/api/health" >/dev/null 2>&1 && break
  sleep 3
done
curl -fsS "http://127.0.0.1:${port}/api/health" >/dev/null

docker image prune -f >/dev/null  # drop superseded build layers
echo "$target" > .deployed-sha
rm -f .deploy-failed-sha
log "deployed ${target:0:7} — http://127.0.0.1:${port}"
